name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./week_6_github_actions
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Build container
      run: |
        docker network create data
        docker build --tag inference:latest .
        docker run -d -p 8000:8000 --network data --name inference_container inference:latest
        curl -X 'GET' \
        'http://localhost:8000/predict?text=this%20is%20a%20sample%20sentence' \
        -H 'accept: application/json'